In [6]:
import h5py
import numpy as np
import os
import spectre.IO.H5 as spectreh5
import spectre.DataStructures as spectreds
import spectre.Spectral as spectral
import spectre



# Spectre Data

In [4]:
pwd = os.getcwd()
f = h5py.File(pwd + "/SpectreVolumeData/PlaneWaveMinkowski3DLowResVolume0.h5","r")
f.keys()

<KeysViewHDF5 ['VolumePsi.vol', 'src.tar.gz']>

In [5]:
VolumePsi = f.get("VolumePsi.vol")
src = f.get("src.tar.gz")

In [6]:
VolumePsi.keys()

<KeysViewHDF5 ['ObservationId8897018137866553916']>

In [7]:
ObsId = VolumePsi.get('ObservationId8897018137866553916')

In [8]:
ObsId.keys()

<KeysViewHDF5 ['InertialCoordinates_x', 'InertialCoordinates_y', 'InertialCoordinates_z', 'Psi', 'bases', 'connectivity', 'grid_names', 'quadratures', 'total_extents']>

In [32]:
x = np.array(ObsId.get('InertialCoordinates_x'))
y = np.array(ObsId.get('InertialCoordinates_y'))
z = np.array(ObsId.get('InertialCoordinates_z'))
psi = np.array(ObsId.get('Psi'))
print(x, y, z)
print(psi)

[0. 1. 0. 1. 0. 1. 0. 1.] [0. 0. 1. 1. 0. 0. 1. 1.] [0. 0. 0. 0. 1. 1. 1. 1.]
[0.         0.84147098 0.84147098 0.90929743 0.84147098 0.90929743
 0.90929743 0.14112001]


# Einstein Toolkit data

In [24]:
ETdata = h5py.File("ETK_data/ETK_phi.h5", "r")
ETxfile = h5py.File("ETK_data/x.h5", "r")
ETyfile = h5py.File("ETK_data/y.h5", "r")
ETzfile = h5py.File("ETK_data/z.h5", "r")
ETdata.keys()

<KeysViewHDF5 ['Cactus Parameters', 'GRID::x timelevel 0 at iteration 0', 'Global Attributes']>

In [34]:
grid_x = ETxfile.get('GRID::x timelevel 0 at iteration 0')
grid_x_arr = np.array(grid_x)
print(grid_x_arr)
grid_x_arr_flat = grid_x_arr.flatten()
print(grid_x_arr_flat)
grid_y = ETyfile.get('GRID::y timelevel 0 at iteration 0')
grid_y_arr = np.array(grid_y)
print(grid_y_arr)
grid_z = ETzfile.get('GRID::z timelevel 0 at iteration 0')
grid_z_arr = np.array(grid_z)
print(grid_z_arr)

[[[-0.15  0.15]
  [-0.15  0.15]]

 [[-0.15  0.15]
  [-0.15  0.15]]]
[-0.15  0.15 -0.15  0.15 -0.15  0.15 -0.15  0.15]
[[[-0.15 -0.15]
  [ 0.15  0.15]]

 [[-0.15 -0.15]
  [ 0.15  0.15]]]
[[[-0.15 -0.15]
  [-0.15 -0.15]]

 [[ 0.15  0.15]
  [ 0.15  0.15]]]


In [17]:
!rm testing.h5
spectre_h5 = spectreh5.H5File("testing.h5", "w-")
vol_file = spectre_h5.insert_vol("/volume_data", 0)
datastuff = spectreds.TensorComponent("blah", spectreds.DataVector(np.array([0.1])))
element_data = spectreds.ElementVolumeData([3], [datastuff], [spectral.Basis.FiniteDifference], [spectral.Quadrature.CellCentered], "element name")
vol_file.write_volume_data(0, 0.5, [element_data])
spectre_h5.close()

RuntimeError: 
############ ERROR ############
Shortened stack trace is:
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(_ZNK2h56H5FileILNS_10AccessTypeE0EE3getINS_10VolumeDataEJEEERKT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEDpOT0_+0x1f5) [0x7f24bc656a55] Address for addr2line: 0xb6a55
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(_ZZN11py_bindings16bind_h5file_implILN2h510AccessTypeE0EEEvRN8pybind117module_EENKUlRKNS1_6H5FileILS2_0EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE0_clES9_SH_+0x21) [0x7f24bc656851] Address for addr2line: 0xb6851
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(+0xb680f) [0x7f24bc65680f] Address for addr2line: 0xb680f
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(+0xb6796) [0x7f24bc656796] Address for addr2line: 0xb6796
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(+0xb66c7) [0x7f24bc6566c7] Address for addr2line: 0xb66c7
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(+0xb65d5) [0x7f24bc6565d5] Address for addr2line: 0xb65d5
/home/knelli/Documents/research/spectre/build/bin/python/spectre/IO/H5/_PyH5.so(+0x78ee1) [0x7f24bc618ee1] Address for addr2line: 0x78ee1
/bin/python3(+0x15b76e) [0x563cabafe76e] Address for addr2line: 0x15b76e
/bin/python3(_PyObject_MakeTpCall+0x25b) [0x563cabaf530b] Address for addr2line: 0x15230b
/bin/python3(+0x16999b) [0x563cabb0c99b] Address for addr2line: 0x16999b
End shortened stack trace.

Node: 0 Proc: 0
Line: 220 of /home/knelli/Documents/research/spectre/src/IO/H5/File.hpp
Function: const ObjectType &h5::H5File<h5::AccessType::ReadWrite>::get(const std::string &, Args &&...) const [Access_t = h5::AccessType::ReadWrite, ObjectType = h5::VolumeData, Args = <>]
Object /volume_data already open. Cannot open object /volume_data.
############ ERROR ############



In [22]:
cactus_param = np.array(ETdata.get('Cactus Parameters/All Parameters'))
print (cactus_param.shape)

(655,)


In [18]:
global_attr = ETdata.get('Global Attributes')
global_attr

<HDF5 group "/Global Attributes" (0 members)>

In [19]:
t0 = np.array(ETdata.get( 'WAVETOY::phi timelevel 0 at iteration 0'))
t0

array([[[0.99142726, 0.99142726],
        [0.99142726, 0.99142726]],

       [[0.99142726, 0.99142726],
        [0.99142726, 0.99142726]]])

In [20]:
print (t0)

[[[0.99142726 0.99142726]
  [0.99142726 0.99142726]]

 [[0.99142726 0.99142726]
  [0.99142726 0.99142726]]]
